version: '3.9'

services:
  backend:
    &dev_backend
    build:
      context: .
      args:
        extra_pipenv_args: --dev
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app/
    restart: unless-stopped
    entrypoint: "./manage.py runserver 0.0.0.0:8000"

  celery_worker:
    <<: *dev_backend
    ports:
      - "8000"
    depends_on:
      - backend
      - db
      - redis
    entrypoint: "celery -A project worker -l info"
    restart: unless-stopped

  celery_beat:
    <<: *dev_backend
    ports:
      - "8000"
    depends_on:
      - backend
      - db
      - redis
    entrypoint: "celery -A project beat -l info"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kync_dev

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1"]


volumes:
  db-data:
  redis-data:
