# Generated by Django 4.2.1 on 2023-05-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="host",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ssh_user",
        ),
        migrations.AlterField(
            model_name="project",
            name="groups",
            field=models.ManyToManyField(blank=True, default="", related_name="projects", to="sync.group"),
        ),
        migrations.AlterField(
            model_name="project",
            name="persons",
            field=models.ManyToManyField(blank=True, default="", related_name="projects", to="sync.person"),
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("ssh_user", models.CharField(default="ubuntu", max_length=50)),
                ("comment", models.TextField(blank=True, help_text="This will be added in the key files on server")),
                ("internal_comment", models.TextField(blank=True, help_text="Only for administration")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="environments", to="sync.project"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
