# Generated by Django 3.2.5 on 2021-07-21 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    def create_default_user(apps, schema_editor):
        User = apps.get_model("custom_auth", "User")

        User.objects.create_superuser(username="admin", email="admin@smf.ai", password="admin")

    operations = [
        migrations.RunPython(create_default_user),
    ]
